public class updateAccountClass
{
  /*  public void publishEvent(Id AccountId)
    {
        Account accntObj =[select id,CustomerPriority__c from Account where Id=:AccountId];
        accntObj.CustomerPriority__c='High';
        update accntObj;
             Demo_PE__e eventObj = new Demo_PE__e(Account_Id__c =accntObj.id);
             Database.saveResult sr = EventBus.publish(eventObj);
             if(sr.isSuccess())
         {
        System.debug('event subscribed successfully');
             }
             else
             {
            System.debug('error subscribed successfully');
             }
        }*/
}